import base64
import html
import json
from datetime import datetime, timezone

DIRECT_SITES = [
    'domain:mtalk.google.com',
    'domain:push.apple.com',
    'domain:api.push.apple.com',
    'domain:push-apple.com.akadns.net',
    'domain:courier.push.apple.com',
    'domain:yandex.com',
    'domain:yandex.net',
    'domain:yandex.ru',
    'domain:ya.ru',
    'domain:yastatic.net',
    'domain:mail.ru',
    'domain:my.mail.ru',
    'domain:e.mail.ru',
    'domain:mrgcdn.ru',
    'domain:my.com',
    'domain:vk.com',
    'domain:vk.ru',
    'domain:vk.me',
    'domain:vkontakte.ru',
    'domain:vkuservideo.net',
    'domain:vkuseraudio.net',
    'domain:vk-cdn.net',
    'domain:vk.company',
    'domain:userapi.com',
    'domain:vk.cc',
    'domain:vkuser.net',
    'domain:vk.video',
    'domain:vk-portal.net',
    'domain:vk-portal.org',
    'domain:vk-apps.com',
    'domain:vkpay.ru',
    'domain:vkforms.ru',
    'domain:vkmessenger.com',
    'domain:ok.ru',
    'domain:okcdn.ru',
    'domain:ok.me',
    'domain:odkl.ru',
    'domain:odnoklassniki.ru',
    'domain:mycdn.me',
    'domain:max.ru',
    'domain:oneme.ru',
    'domain:media.max.ru',
    'domain:static.max.ru',
    'domain:messenger.max.ru',
    'domain:st.max.ru',
    'domain:ic1.max.ru',
    'domain:ic2.max.ru',
    'domain:ic3.max.ru',
    'domain:ic4.max.ru',
    'domain:i.oneme.ru',
    'domain:ws-api.oneme.ru',
    'domain:calls.okcdn.ru',
    'domain:sberbank.ru',
    'domain:sber.ru',
    'domain:sbrf.ru',
    'domain:online.sberbank.ru',
    'domain:id.sber.ru',
    'domain:tinkoff.ru',
    'domain:tbank.ru',
    'domain:tcsbank.ru',
    'domain:cdn-tinkoff.ru',
    'domain:t-bank-app.ru',
    'domain:acdn.tinkoff.ru',
    'domain:api.tinkoff.ru',
    'domain:alfabank.ru',
    'domain:vtb.ru',
    'domain:rosbank.ru',
    'domain:gazprombank.ru',
    'domain:raiffeisen.ru',
    'domain:psbank.ru',
    'domain:open.ru',
    'domain:nspk.ru',
    'domain:qr.nspk.ru',
    'domain:mironline.ru',
    'domain:homecredit.ru',
    'domain:sovcombank.ru',
    'domain:gosuslugi.ru',
    'domain:nalog.gov.ru',
    'domain:mos.ru',
    'domain:government.ru',
    'domain:kremlin.ru',
    'domain:ozon.ru',
    'domain:wildberries.ru',
    'domain:wb.ru',
    'domain:avito.ru',
    'domain:avito.st',
    'domain:vkusvill.ru',
    'domain:2gis.com',
    'domain:2gis.ru',
    'domain:dns-shop.ru',
    'domain:mvideo.ru',
    'domain:citilink.ru',
    'domain:lamoda.ru',
    'domain:sbermegamarket.ru',
    'domain:mts.ru',
    'domain:megafon.ru',
    'domain:beeline.ru',
    'domain:tele2.ru',
    'domain:rt.ru',
    'domain:rostelecom.ru',
    'domain:mangabuff.ru',
    'domain:api.ipify.org',
    'domain:checkip.amazonaws.com',
    'domain:ifconfig.me',
    'domain:ip.mail.ru',
    'domain:ipv4-internet.yandex.net',
    'domain:ipv6-internet.yandex.net',
    'domain:101hotels.com',
    'domain:alfa.me',
    'domain:appsflyersdk.com',
    'domain:avito.com',
    'domain:beget.com',
    'domain:championat.com',
    'domain:chizhik.club',
    'domain:cian.com',
    'domain:drweb.com',
    'domain:eda.yandex',
    'domain:fon.bet',
    'domain:gett.com',
    'domain:gismeteo.com',
    'domain:go.yandex',
    'domain:group-ib.com',
    'domain:icq.com',
    'domain:icq.im',
    'domain:icq.net',
    'domain:interfax.com',
    'domain:ixbt.com',
    'domain:joom.com',
    'domain:kaspersky.com',
    'domain:kontur.host',
    'domain:lavka.yandex',
    'domain:lenta.com',
    'domain:livejournal.com',
    'domain:mail.ru',
    'domain:maps.me',
    'domain:match.tv',
    'domain:mediascope.net',
    'domain:megamarket.tech',
    'domain:megogo.net',
    'domain:moex.com',
    'domain:more.tv',
    'domain:mradx.net',
    'domain:mts.com',
    'domain:myicq.com',
    'domain:mytarget.com',
    'domain:mytracker.com',
    'domain:mytrackerapi.com',
    'domain:okko.tv',
    'domain:onetwotrip.com',
    'domain:ostin.com',
    'domain:otkritie.ru',
    'domain:ozon.st',
    'domain:ozon.travel',
    'domain:ozoncloud.net',
    'domain:ozonusercontent.com',
    'domain:pobeda.aero',
    'domain:positive-tech.com',
    'domain:premier.one',
    'domain:ptsecurity.com',
    'domain:qiwi.com',
    'domain:ren.tv',
    'domain:rt.com',
    'domain:russian.rt.com',
    'domain:selectel.com',
    'domain:sputnikglobe.com',
    'domain:sputniknews.com',
    'domain:tamtam.chat',
    'domain:tilda.cc',
    'domain:tilda.ws',
    'domain:tildaapi.com',
    'domain:timeweb.com',
    'domain:toloka.ai',
    'domain:uralairlines.com',
    'domain:vk-cdn.me',
    'domain:vk.cloud',
    'domain:vk.link',
    'domain:vkplay.live',
    'domain:wbstatic.net',
    'domain:wildberries.kz',
    'domain:ya.cc',
    'domain:yadi.sk',
    'domain:yandex.az',
    'domain:yandex.by',
    'domain:yandex.cloud',
    'domain:yandex.com.tr',
    'domain:yandex.ee',
    'domain:yandex.fr',
    'domain:yandex.kz',
    'domain:yandex.lt',
    'domain:yandex.lv',
    'domain:yandex.md',
    'domain:yandex.tj',
    'domain:yandex.tm',
    'domain:yandex.ua',
    'domain:yandex.uz',
    'domain:yandexadexchange.net',
    'domain:yandexcloud.net',
    'domain:yango.com',
    'domain:yappy.media',
    'domain:youdrive.today',
    'domain:zvuk.com',
]


def profile():
    return {
        'Name': 'FOCUSLENS: direct Russian services',
        'GlobalProxy': 'true',
        'RemoteDNSType': 'DoH',
        'RemoteDNSDomain': 'https://cloudflare-dns.com/dns-query',
        'RemoteDNSIP': '1.1.1.1',
        'DomesticDNSType': 'DoH',
        'DomesticDNSDomain': 'https://common.dot.dns.yandex.net/dns-query',
        'DomesticDNSIP': '77.88.8.8',
        'Geoipurl': '',
        'Geositeurl': '',
        'LastUpdated': str(int(datetime.now(timezone.utc).timestamp())),
        'DnsHosts': {},
        'DirectSites': DIRECT_SITES,
        'DirectIp': [
            '192.168.0.0/24',
            '10.8.0.0/24',
            '127.0.0.0/8',
            '169.254.0.0/16',
        ],
        'ProxySites': [],
        'ProxyIp': [],
        'BlockSites': [],
        'BlockIp': [],
        'DomainStrategy': 'IPIfNonMatch',
        'FakeDNS': 'false',
    }


def json_text():
    return json.dumps(profile(), ensure_ascii=False, indent=2)


def deeplink():
    payload = json.dumps(profile(), ensure_ascii=False, separators=(',', ':')).encode('utf-8')
    return 'happ://routing/add/' + base64.b64encode(payload).decode('ascii')


def page():
    link = deeplink()
    return f'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>HAPP routing | FOCUSLENS.DEV</title><link rel="icon" href="/favicon.png"><style>
body{{margin:0;background:#050816;color:#f5f7ff;font:16px/1.5 Inter,"Segoe UI",sans-serif;padding:32px}}main{{max-width:980px;margin:auto}}.panel{{background:#111b34e0;border:1px solid #ffffff1f;padding:24px;box-shadow:0 20px 40px #0006}}h1{{margin:0 0 8px}}p,small{{color:#8ea0be}}a.button{{display:inline-block;background:linear-gradient(135deg,#7c3aed,#22d3ee);color:#fff;padding:12px 16px;border-radius:4px;text-decoration:none;font-weight:700}}pre{{white-space:pre-wrap;overflow-wrap:anywhere;background:#050816;border:1px solid #ffffff1f;padding:16px;font:12px/1.45 Consolas,monospace}}.meta{{display:flex;gap:16px;flex-wrap:wrap;color:#8ea0be}}
</style></head><body><main><section class="panel"><p>FOCUSLENS.DEV / HAPP</p><h1>Direct Russian services</h1><p>Импортируйте routing-профиль в HAPP. Список доменов идёт напрямую с устройства, остальной трафик остаётся через текущий proxy-профиль.</p><div class="meta"><span>DirectSites: {len(DIRECT_SITES)}</span><span>GlobalProxy: true</span><span>LAN: direct</span></div><p><a class="button" href="{html.escape(link, quote=True)}">Открыть в HAPP</a></p><small>Если приложение не открылось, скопируйте deeplink вручную:</small><pre>{html.escape(link)}</pre><details><summary>JSON routing profile</summary><pre>{html.escape(json_text())}</pre></details></section></main></body></html>'''
